version: "3.9"

services:
  security-service:
    depends_on:
      postgres:
        condition: service_healthy
    image: svhd/logto:${TAG-latest}
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    ports:
      - 3001:3001
      - 3002:3002
    environment:
      - TRUST_PROXY_HEADER=1
      - DB_URL=postgres://postgres:p0stgr3s@postgres:5432/logto
      - ENDPOINT
      - ADMIN_ENDPOINT
    networks:
      - logto-network

  postgres:
    image: postgres:14-alpine
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr3s
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - logto-network
      
  pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        networks:
            - logto-network
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@logto.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
networks:
  logto-network:
    driver: bridge
